name: 'kaniko - Build Images In Kubernetes'
description: 'GitHub Action for build/push Docker Images with Kaniko.'
author: 'ByMarshall <montillajcx@gmail.com>'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  context:
    description: 'Path to the build context. Default to the workspace'
    required: false
  file:
    description: 'Path to the Dockerfile. Default to Dockerfile. It must be in the context. If set, this action passes the relative path to Kaniko, same as the behavior of docker build	--dockerfile'
    required: false
  push:
    description: "Push an image to the registry. Default to true"
    required: false
    default: 'true'
  tags:
    description: "List of tags."
    required: true
  labels:
    description: "List of metadata labels for an image."
    required: false
  tar_file:
    description: "Tarball name to save the image, the file is saved into Workspace by default."
    required: false
  build_args:
    description: 'Space separated list of extra build-args (build-time variables)'
    required: false
  debug_mode:
    description: 'Set debug mode true to display the command line and parameters that has been used to build the image. Warning!! some sensitive data used to build the image may will be exposed.'
    required: false
    default: 'false'
  cache:
    description: 'Set this flag as true to opt into caching with kaniko.'
    required: false
    default: 'false'
  cache_ttl:
    description: Cache timeout in hours. Defaults to 12h.
    required: false
    default: '12h'
  snapshot_mode:
    description: Set this flag to set how kaniko will snapshot the filesystem (full, redo, time). Default to full.
    required: false
    default: 'full'
  use_new_run:
    description: Use the experimental run implementation for detecting changes without requiring file system snapshots. In some cases, this may improve build performance by 75%.
    required: false
    default: 'false'
runs:
  using: 'docker'
  image: 'Dockerfile'