name: 'kaniko - Build Images In Kubernetes'
description: 'GitHub Action for build/push Docker Images with Kaniko.'
author: 'ByMarshall <montillajcx@gmail.com>'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  context:
    description: 'Path to the build context. Default to the workspace'
    required: false
  file:
    description: 'Path to the Dockerfile. Default to Dockerfile. It must be in the context. If set, this action passes the relative path to Kaniko, same as the behavior of docker build	--dockerfile'
    required: false
  push:
    description: "Push an image to the registry. Default to true"
    required: false
    default: 'true'
  tags:
    description: "List of tags."
    required: true
  labels:
    description: "List of metadata labels for an image."
    required: false
  tar_file:
    description: "Tarball name to save the image, the file is saved into Workspace by default."
    required: false
  build-args:
    description: 'Extra build-args'
    required: false
  kaniko-args:
    description: 'Extra arguments for the CLI command'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'